export const STOPWORDS = new Set<string>([
  'the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i', 'it', 'for',
  'not', 'on', 'with', 'he', 'as', 'you', 'do', 'at', 'this', 'but', 'his',
  'by', 'from', 'they', 'we', 'say', 'her', 'she', 'or', 'an', 'will', 'my',
  'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if',
  'about', 'who', 'get', 'which', 'go', 'me', 'when', 'make', 'can', 'like',
  'time', 'no', 'just', 'him', 'know', 'take', 'people', 'into', 'year', 'your',
  'good', 'some', 'could', 'them', 'see', 'other', 'than', 'then', 'now', 'look',
  'only', 'come', 'its', 'over', 'think', 'also', 'back', 'after', 'use', 'two',
  'how', 'our', 'work', 'first', 'well', 'way', 'even', 'new', 'want', 'because',
  'any', 'these', 'give', 'day', 'most', 'us', 'is', 'are', 'was', 'were',
  'been', 'has', 'had', 'does', 'did', 'been', 'being', 'am', 'having',
  'should', 'would', 'could', 'might', 'must', 'shall', 'may', 'will', 'can',
  'need', 'dare', 'ought', 'used', 'does', 'did', 'has', 'had', 'having',
  'been', 'being', 'is', 'are', 'was', 'were', 'am', 'be', 'being', 'been',
  'very', 'much', 'more', 'most', 'less', 'least', 'few', 'many', 'such',
  'same', 'other', 'another', 'each', 'every', 'both', 'either', 'neither',
  'between', 'among', 'through', 'during', 'before', 'after', 'above',
  'below', 'under', 'over', 'again', 'further', 'once', 'here', 'there',
  'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most',
  'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so',
  'than', 'too', 'very', 's', 't', 'd', 'll', 'm', 'o', 're', 've', 'y',
  'ain', 'aren', 'couldn', 'didn', 'doesn', 'hadn', 'hasn', 'haven', 'isn',
  'ma', 'mightn', 'mustn', 'needn', 'shan', 'shouldn', 'wasn', 'weren',
  'won', 'wouldn', 'let', 'got', 'getting', 'put', 'set', 'get', 'getting',
  'however', 'therefore', 'thus', 'hence', 'while', 'although', 'though',
  'since', 'unless', 'until', 'whether', 'within', 'without', 'upon', 'onto',
  'into', 'from', 'toward', 'towards', 'along', 'across', 'around', 'behind',
  'beside', 'besides', 'beyond', 'inside', 'outside', 'near', 'against',
  'off', 'down', 'away', 'back', 'forth', 'together', 'apart', 'aside',
  'page', 'chapter', 'section', 'figure', 'table', 'fig', 'etc', 'eg', 'ie',
  'via', 'per', 'qua', 'pro', 'con', 're', 'de', 'la', 'le', 'el', 'los',
  'las', 'un', 'une', 'des', 'du', 'da', 'di', 'del', 'al', 'en', 'yo',
  'tu', 'su', 'nous', 'vous', 'il', 'elle', 'on', 'nous', 'vous', 'ils',
  'elles', 'se', 'me', 'te', 'lui', 'leur', 'y', 'en',
]);
